site_name: Showstock
site_url: https://lyndsysimon.github.io/showstock/
repo_url: https://github.com/lyndsysimon/showstock
repo_name: showstock

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.annotate
    - content.code.copy
    - content.tooltips

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - API Documentation: api.md
  - Development: development.md
